---
# control
control:
  num_users: '8'
  assist_mode: 'stack'
  local_epoch: '10'
  global_epoch: '10'
  assist_rate_mode: 'search'
  noise: '0'
  al: '0'
  rl: 'none'
  dl: '1'
  pl: 'none'
# data
data_name: CIFAR10
# MNIST
model_name: conv
# experiment
pin_memory: False
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
# backdoor
backdoor:
  # attack: 'ftrojan'
  attack: 'badnet'
  num_attackers: 1
  poison_percent: 0.04
  target_class: 1
  poison_data: False
mark:
  # badnet
  mark_path: 'apple_black.png'
  width_offset: -4
  # ftrojan
  YUV: True
  channel_list: [1, 2]
  pos_list: 
  - [31, 31]
  - [15, 15]
  magnitude: 30
defense:
  detect_anomalies: True
  mode: 'isolation_forest'
